(#420) updated saving/added highlighting on partially mapped
t3-innovation-network/desm pull request #462
Opened 2024-02-18 21:01 UTC by shlag3n

#420

* updated mapping saving (will save what is possible and always on)
* added highlighting to partially mapped items
* improved error messaging
* fixed blank screen on changelog/back buttons
* fixed saving mappings for shared mappings
* fixed some react related issues with mutating state

2024-02-21 06:03 UTC, excelsior requested changes
There are some issues (although not all of them belong to the scope of the task, I guess):

1. Saving a mapping with fully unmapped terms gives this error:

<img width="684" alt="Screenshot 2024-02-21 at 10 23 34" src="https://github.com/t3-innovation-network/desm/assets/406292/cbcc2eb0-771b-40e4-989c-7030d56a00b7">

2. If the above alert is closed, no subsequent errors are shown.
3. It doesn't seem possible to unmap a term.
4. Alignments with a `No Match` predicate are highlighted as partial (but get saved as expected).
5. It's possible to save a `No Match` alignment with a mapped term, though.
6. As far as I can see, partial alignments do get saved, so the success message is a bit misleading.

2024-02-21 18:16 UTC, shlag3n commented on app/controllers/api/v1/alignments_controller.rb
> +        interactor = SaveAlignments.call(alignments: alignments_params, mapping: mapping)
good point, will address this separately and rebase this branch with main after that

2024-02-21 18:33 UTC, shlag3n commented
> There are some issues (although not all of them belong to the scope of the task, I guess):
> 
> 1. Saving a mapping with fully unmapped terms gives this error:
> 2. If the above alert is closed, no subsequent errors are shown.
1, 2 - will fix and let you know

> 3. It doesn't seem possible to unmap a term.
We're collecting these things at notion - https://www.notion.so/learningtapestry/Q-A-1a06bee62f9248cb8751ff29efc21ce4, feel free to add there (this one already was added and it's not related to the task)

> 4. Alignments with a `No Match` predicate are highlighted as partial (but get saved as expected).
4 - will fix

> 5. It's possible to save a `No Match` alignment with a mapped term, though.
This is question at notion

> 6. As far as I can see, partial alignments do get saved, so the success message is a bit misleading.
Partial alignments will not be saved, only completed will be but you can click save at any moment and that was one of the requirement.

2024-02-22 16:48 UTC, shlag3n commented
@excelsior p.2 was moved to https://github.com/t3-innovation-network/desm/issues/466

2024-02-23 06:12 UTC, excelsior commented
Re: 6, partial alignments get saved but only under certain circumstances. Attached is a screencast demoing one of such cases (there are may be others).

https://github.com/t3-innovation-network/desm/assets/406292/b31e1105-6fe2-405f-b9d8-ca6b479a4efd

2024-02-23 13:06 UTC, excelsior commented
I see. Everything else works as expected, thanks!

2024-02-23 13:06 UTC, excelsior approved these changes

2024-03-06 15:24 UTC, merged