Feature/implement sort options in property mappings list
t3-innovation-network/desm pull request #73
Opened 2020-12-11 16:28 UTC by richard0000

# What was done?

-----

### Define structure of sorting spine properties

### Implement the different alignment sorting criteria
- On the "Synthetic Spine Property Mapping By Category" screen, looking at the issue #71, implement the different criteria for sorting the alignments to a spine term.

### Ensure every property has its selectable domains collection
- Since different organizations specifies the available domain list for a property differently, we take care of ensuring that, in the end, we have a collection of string values to show the user in the edit term screen.

### Complete the spine sort options implementation
Options to sort spine properties available:
- "Overall Alignment Score"
- "Organization"
- "Spine Class/Type"
- "Spine Property"
- "Total Identical Alignments"

### Complete the alignment sort options implementation
Options to sort alignments available:
- "Organization"
- "Class/Type"
- "Alignment Score"
- "Property"
- "Has Alignment Issues"

### Options still unavailable for sorting spine terms (awaiting requirement clarifications)
- "Has Alignment Issues"
- "Source Data Order"

2020-12-11 19:00 UTC, stuartasutton commented
I thought I had resolved the two open matters: (1) "Has Alignment Issues" on spine; and (2) "Source Data Order" on alignment sort.  The "Source Data Order" is irrelevant here since it relates to the ordering in the old spreadsheets. The "Has Alignment Issues" on spine sort puts those properties with issues at the top of the list.

2020-12-13 17:32 UTC, excelsior requested changes

2020-12-13 17:32 UTC, excelsior commented on app/javascript/components/mapping-to-domains/TermCard.jsx
>              (disableClick ? "" : selected ? "" : " cursor-pointer")
Again, better avoid nested ternary operators as they're not always easy to read. Here, a single expression can be used: `disableClick || selected ? "" : " cursor-pointer"`.

2020-12-13 17:32 UTC, excelsior commented on app/javascript/components/property-mapping-list/PropertiesList.jsx
> +    this.setState({ properties: [...properties] });
`properties` is an array already, no need to re-expand it. I believe, it can be shortened to `this.setState({ properties })`.

2020-12-13 17:32 UTC, excelsior commented on db/migrate/20201210183833_add_selected_domain_to_existent_properties.rb
> +    Property.all.each do |p|
This can be done at once, without looping through all of the properties:

`Property.update_all("selected_domain = domain->>0")`

2020-12-13 17:32 UTC, excelsior commented on db/schema.rb
> +    t.string "color"
Where does this column come from? There is no migration with it.

2020-12-14 16:45 UTC, merged